# RSPE01 - Wii Sports Optimized Settings

[Core]
CPUThread = True
Fastmem = True
DSPHLE = True
SyncGPU = False
SyncOnSkipIdle = False

[Video_Settings]
InternalResolution = 1
WaitForShadersBeforeStarting = False
ShaderCompilationMode = 0

[Video_Hacks]
EFBToTextureEnable = True
EFBAccessEnable = False
EFBScaledCopy = True
FastDepthCalc = True
BBoxEnable = False
